# Generated by Django 4.0.1 on 2022-02-20 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer_task',
            name='submissiondate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
