# Generated by Django 4.0.1 on 2022-02-23 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_attendance_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_registration',
            name='TL_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user_registration',
            name='projectmanager_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
