# Generated by Django 4.0.1 on 2022-02-23 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_user_registration_tl_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_taskassign',
            name='extension',
            field=models.IntegerField(default='0'),
        ),
    ]
